CREATE OR REPLACE TABLE ANALYTICS_LAYER.DAILY_REJECTED_CLAIMS
AS
SELECT 
TRY_TO_DATE(CLAIM_DATE) AS CLAIM_DATE,
COUNT(*) AS REJECTED_CLAIM_COUNT
FROM VALIDATED_LAYER.BAD_CLAIMS
GROUP BY TRY_TO_DATE(CLAIM_DATE);

SELECT * FROM DAILY_REJECTED_CLAIMS;

SELECT PROVIDER_ID, CLAIM_ID, AMOUNT,
    TRY_TO_DATE(CLAIM_DATE) AS CLAIM_DATE,
    COUNT(*) OVER (
        PARTITION BY PROVIDER_ID
        ORDER BY TRY_TO_DATE(CLAIM_DATE)
        RANGE BETWEEN INTERVAL '7 DAY' PRECEDING AND CURRENT ROW
    ) AS HIGH_CLAIM_COUNT_7_DAYS,
    CASE 
        WHEN AMOUNT > 50000
         AND COUNT(*) OVER (
            PARTITION BY PROVIDER_ID
            ORDER BY TRY_TO_DATE(CLAIM_DATE)
            RANGE BETWEEN INTERVAL '7 DAY' PRECEDING AND CURRENT ROW
        ) > 1
        THEN 'FRAUD_SUSPECTED'
        ELSE 'NORMAL'
    END AS FRAUD_FLAG
FROM CURATED_LAYER.STG_CLAIMS
WHERE AMOUNT > 50000;

SELECT COUNT(*) FROM CURATED_LAYER.FACT_CLAIMS; 

SELECT COUNT(*) AS valid_claims
FROM CURATED_LAYER.FACT_CLAIMS
WHERE FRAUD_FLAG = 'N';
