CREATE OR REPLACE DYNAMIC TABLE CURATED_LAYER.STG_CLAIMS
TARGET_LAG = 'DOWNSTREAM'
WAREHOUSE = COMPUTE_WH
AS 
SELECT 
CLAIM_ID, PROVIDER_ID, PROCEDURE_CODE, AMOUNT, 
TRY_TO_DATE(CLAIM_DATE) AS CLAIM_DATE
FROM VALIDATED_LAYER.CLAIMS_VALIDATED;

SELECT * FROM CURATED_LAYER.STG_CLAIMS;

CREATE OR REPLACE DYNAMIC TABLE CURATED_LAYER.FACT_CLAIMS
TARGET_LAG = '1 MINUTE'
WAREHOUSE = COMPUTE_WH
AS 
SELECT 
C.CLAIM_ID, P.PATIENT_ID , C.PROVIDER_ID, C.PROCEDURE_CODE, C.AMOUNT, 
TRY_TO_DATE(C.CLAIM_DATE) AS CLAIM_DATE,
CASE 
    WHEN C.AMOUNT > 50000 
    OR COUNT(*) OVER (
              PARTITION BY PROVIDER_ID, PROCEDURE_CODE
              ORDER BY TRY_TO_DATE(CLAIM_DATE)
              RANGE BETWEEN INTERVAL '7 DAY' PRECEDING AND CURRENT ROW) > 1
    THEN 'Y'
    ELSE 'N'
    END AS FRAUD_FLAG
FROM CURATED_LAYER.STG_CLAIMS C
LEFT JOIN RAW_LAYER.PATIENTS_RAW P
ON C.CLAIM_ID = P.CLAIM_ID;

SELECT * FROM FACT_CLAIMS;


CREATE OR REPLACE MASKING POLICY mask_amount AS (amount NUMBER)
RETURNS NUMBER ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN amount
    ELSE NULL
END;

CREATE OR REPLACE MASKING POLICY mask_procedure AS (PROCEDURE_CODE STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'ANALYST_FULL') THEN PROCEDURE_CODE
    ELSE 'XXXXX'
END;

ALTER TABLE fact_claims
MODIFY COLUMN amount
SET MASKING POLICY mask_amount;

ALTER TABLE fact_claims
MODIFY COLUMN PROCEDURE_CODE
SET MASKING POLICY mask_procedure;

SELECT DISTINCT * FROM FACT_CLAIMS;

