--CREATE DATABSE
CREATE OR REPLACE DATABASE HEALTHCARE_DB; 

--CREATE SCHEMAS
CREATE OR REPLACE SCHEMA RAW_LAYER;
CREATE OR REPLACE SCHEMA VALIDATED_LAYER;
CREATE OR REPLACE SCHEMA CURATED_LAYER;
CREATE OR REPLACE SCHEMA ANALYTICS_LAYER;

USE SCHEMA RAW_LAYER;

--CREATE STAGE
CREATE OR REPLACE STAGE MY_STAGE;

--CREATED CSV_FORMAT
CREATE OR REPLACE FILE FORMAT RAW_LAYER.CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

--CREATE CLAIMS TABLE
CREATE OR REPLACE TABLE RAW_LAYER.CLAIMS_RAW (
    CLAIM_ID STRING,
    AMOUNT NUMBER,
    PROVIDER_ID STRING,
    PROCEDURE_CODE STRING,
    CLAIM_DATE STRING
);

--CREATE PATIENTS TABLE
CREATE OR REPLACE TABLE RAW_LAYER.PATIENTS_RAW
(
    PATIENT_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    DATE_OF_BIRTH DATE,
    GENDER STRING,
    PHONE NUMBER,
    CITY STRING,
    STATE STRING,
    CLAIM_ID VARCHAR
);

-- CREATE PROVIDER DATA
CREATE OR REPLACE TABLE RAW_LAYER.PROVIDER_DATA
(
    PROVIDER_ID VARCHAR,
    PROVIDER_NAME VARCHAR,
    DEPARTMENT VARCHAR
);

LIST @MY_STAGE;

COPY INTO RAW_LAYER.CLAIMS_RAW
FROM @MY_STAGE/CLAIMS_HealthCare.csv
FILE_FORMAT = RAW_LAYER.CSV_FORMAT;

COPY INTO RAW_LAYER.PATIENTS_RAW
FROM @MY_STAGE/PATIENT_MASTER_HealthCare.csv
FILE_FORMAT = (FORMAT_NAME = RAW_LAYER.CSV_FORMAT
DATE_FORMAT = 'DD-MM-YYYY');

COPY INTO RAW_LAYER.PROVIDER_DATA
FROM @MY_STAGE/PROVIDER_MASTER_HealthCare.csv
FILE_FORMAT = RAW_LAYER.CSV_FORMAT;

SELECT * FROM RAW_LAYER.CLAIMS_RAW;
SELECT * FROM RAW_LAYER.PATIENTS_RAW;
SELECT * FROM RAW_LAYER.PROVIDER_DATA;

