--CREATING STREAMS AND TASK
CREATE OR REPLACE STREAM CLAIMS_STREAM1
ON TABLE RAW_LAYER.CLAIMS_RAW;

CREATE OR REPLACE STREAM CLAIMS_STREAM2
ON TABLE RAW_LAYER.CLAIMS_RAW;

--INSERTING VALID RECORDS
CREATE OR REPLACE TASK CLAIMS_VALID_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
AS
INSERT INTO VALIDATED_LAYER.CLAIMS_VALIDATED
SELECT C.CLAIM_ID, C.AMOUNT, C.PROVIDER_ID, C.PROCEDURE_CODE, C.CLAIM_DATE
FROM CLAIMS_STREAM1 C
JOIN RAW_LAYER.PROVIDER_DATA PR
ON C.PROVIDER_ID = PR.PROVIDER_ID
WHERE C.AMOUNT > 0 
AND LENGTH(C.PROCEDURE_CODE) = 5
AND C.CLAIM_ID IS NOT NULL;

--INSERTING BAD CLAIMS RECORDS
CREATE OR REPLACE TASK CLAIMS_BAD_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
AS
INSERT INTO VALIDATED_LAYER.BAD_CLAIMS
SELECT C.CLAIM_ID, C.AMOUNT, C.PROVIDER_ID, C.PROCEDURE_CODE, 
CASE 
    --Invalid Amount
    WHEN C.AMOUNT < 0 
    THEN 'Invalid Amount'
    
    --Invalid Procedure code
    WHEN LENGTH(C.PROCEDURE_CODE) != 5 
    THEN 'Invalid Provider'

    --Missing Information 
    WHEN C.CLAIM_ID IS NULL OR
    C.PROVIDER_ID IS NULL OR 
    C.AMOUNT IS NULL 
    THEN 'Missing Information'

    --Duplicate data
    WHEN C.CLAIM_ID IN 
    (SELECT CLAIM_ID 
    FROM RAW_LAYER.CLAIMS_RAW
    GROUP BY CLAIM_ID
    HAVING COUNT(*) >1)
    THEN 'Duplicate Data'
    
    END AS ERROR_REASON
FROM CLAIMS_STREAM2 C 
JOIN RAW_LAYER.PROVIDER_DATA PR
ON C.PROVIDER_ID = PR.PROVIDER_ID
WHERE C.AMOUNT < 0 
OR LENGTH(C.PROCEDURE_CODE) != 5;

ALTER TASK CLAIMS_BAD_TASK RESUME;
ALTER TASK CLAIMS_VALID_TASK RESUME;

-- EXECUTE TASK CLAIMS_BAD_TASK;
-- EXECUTE TASK CLAIMS_VALID_TASK;
