USE DATABASE HEALTHCARE_DB;
USE SCHEMA VALIDATED_LAYER;

--CREATING VALIDATED CLAIMS 
CREATE OR REPLACE TABLE VALIDATED_LAYER.CLAIMS_VALIDATED
LIKE RAW_LAYER.CLAIMS_RAW;

INSERT INTO VALIDATED_LAYER.CLAIMS_VALIDATED
SELECT C.CLAIM_ID, C.AMOUNT, C.PROVIDER_ID, C.PROCEDURE_CODE, C.CLAIM_DATE
FROM RAW_LAYER.CLAIMS_RAW C
LEFT JOIN RAW_LAYER.PROVIDER_DATA PR
ON C.PROVIDER_ID = PR.PROVIDER_ID
WHERE C.AMOUNT > 0 
AND LENGTH(C.PROCEDURE_CODE) = 5
AND C.CLAIM_ID IS NOT NULL;

SELECT * FROM VALIDATED_LAYER.CLAIMS_VALIDATED;

--CREATING BAD CLAIMS DATA
CREATE OR REPLACE TABLE VALIDATED_LAYER.BAD_CLAIMS (
    CLAIM_ID STRING,
    AMOUNT NUMBER,
    PROVIDER_ID STRING,
    PROCEDURE_CODE STRING,
    CLAIM_DATE STRING,
    ERROR_REASON STRING
);

INSERT INTO VALIDATED_LAYER.BAD_CLAIMS
SELECT C.CLAIM_ID, C.AMOUNT, C.PROVIDER_ID, C.PROCEDURE_CODE, C.CLAIM_DATE,
CASE 
    --Invalid Amount
    WHEN C.AMOUNT < 0 
    THEN 'Invalid Amount'
    
    --Invalid Procedure code
    WHEN LENGTH(C.PROCEDURE_CODE) != 5 
    THEN 'Invalid Provider'

    --Missing Information 
    WHEN C.CLAIM_ID IS NULL OR
    C.PROVIDER_ID IS NULL OR 
    C.AMOUNT IS NULL 
    THEN 'Missing Information'

    --Duplicate data
    WHEN C.CLAIM_ID IN 
    (SELECT CLAIM_ID 
    FROM RAW_LAYER.CLAIMS_RAW
    GROUP BY CLAIM_ID
    HAVING COUNT(*) >1)
    THEN 'Duplicate Data'
    
    END AS ERROR_REASON
FROM RAW_LAYER.CLAIMS_RAW C 
LEFT JOIN RAW_LAYER.PROVIDER_DATA PR
ON C.PROVIDER_ID = PR.PROVIDER_ID
WHERE C.AMOUNT < 0 
OR LENGTH(C.PROCEDURE_CODE) != 5;

SELECT * FROM VALIDATED_LAYER.BAD_CLAIMS;

CREATE OR REPLACE TASK daily_task
WAREHOUSE = COMPUTE_WH
SCHEDULE = 10
AS
SELECT CURRENT_TIMESTAMP;

